version: '3'

services:
  database_tmg:
    image: postgres
    container_name: database_fin
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fin_api
    network_mode: host